name: matgary
description: "A new Ecommerce fluuter app using MVC."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get: ^4.6.6
  #DateTime
  jiffy: ^6.2.2
  intl: ^0.19.0
  http: ^1.2.0
  #Images
  cached_network_image: ^3.3.1 
  image_picker: ^1.0.7
  #Animate
  show_up_animation: ^2.0.0
  auto_animated: ^3.2.0
  #Google Map
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  #Firebase And Notification 
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.3.2
  cloud_firestore: ^4.14.0
  #Local Data Cache
  sqflite: ^2.3.1
  shared_preferences: ^2.2.2
  path: ^1.8.3
  #Qrcode 
  qr_flutter: ^4.1.0
  scan: ^1.6.0
  grouped_list: ^5.1.2
  url_launcher: ^6.2.4
  dropdown_search: ^5.0.6
  badges: ^3.1.2
  #Icon 
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  #Google Auth
  google_sign_in: ^6.2.1  
  #device_preview: ^0.7.5
  responsive_builder: ^0.7.0
  image_pickers: ^2.0.4+8
  flutter_otp_text_field: ^1.1.1
  #for failuer lotties images
  lottie: ^3.0.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1



# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
  #       
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: SignikaNegative
      fonts:
        - asset: assets/fonts/SignikaNegative/SignikaNegative-Regular.ttf
        - asset: assets/fonts/SignikaNegative/SignikaNegative-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
